# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3300acdf4700be03aca6aa9fcf99b871cc587f2430c49464f0d6f2adbcd5fefadc25b025783caba3d2a3537a3ce52fb5f73f100ab90a6547381c2291edb4a94c

test:
  secret_key_base: 6f2a3ad3efdac8c786b6cd2b9c9824c954d6a8c92305ccdd2df6d56d47d04ab578b23bf97b60bf8e0654fe474e34d1253b9ac9df53b6be27aca328ce38545739

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
